# Generated by Django 4.0.2 on 2022-02-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdbId', models.IntegerField(verbose_name='imdbId')),
                ('Title', models.CharField(max_length=255, verbose_name='Title')),
                ('Poster', models.CharField(max_length=255, verbose_name='Poster')),
                ('Rating', models.IntegerField(verbose_name='Rating')),
            ],
        ),
    ]
